storeFile=../../../keystore/alouette-debug.keystore
storePassword=android
keyAlias=alouette-debug
keyPassword=android

releaseStoreFile=../../../keystore/alouette-release.keystore
releaseStorePassword=alouette2024
releaseKeyAlias=alouette-release
releaseKeyPassword=alouette2024
