[target.x86_64-linux-android]
linker = "x86_64-linux-android28-clang"
rustflags = [
    "-C", "link-arg=-lc++_shared",
    "-C", "link-arg=-llog",
    "-C", "link-arg=-landroid"
]

[target.aarch64-linux-android]
linker = "aarch64-linux-android28-clang"
rustflags = [
    "-C", "link-arg=-lc++_shared",
    "-C", "link-arg=-llog", 
    "-C", "link-arg=-landroid"
]

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi28-clang"
rustflags = [
    "-C", "link-arg=-lc++_shared",
    "-C", "link-arg=-llog",
    "-C", "link-arg=-landroid"
]

[target.i686-linux-android]
linker = "i686-linux-android28-clang"
rustflags = [
    "-C", "link-arg=-lc++_shared",
    "-C", "link-arg=-llog",
    "-C", "link-arg=-landroid"
]
